// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;

/*module.exports = {
  tutorialSidebar: [
    {
      type: "category",
      label: "Manuales de usuario",
      items: [
              {
                type: "category",
                label: "XIDE", 
                items: [
                        {
                           type: "category",
                           label: "X-NODEs", 
                           items: [                          
                                  {
                                    type: "category",
                                    label: "XC01 - MCU WIFI BLE",
                                    items: [
                                             {
                                              type: "category",
                                              label: "R4", 
                                              items: ["user-manuals/xide/x-nodes/xc01-mcu-wifi-ble/r4/xc01-mcu-wifi-ble-esp32-wroom-32-r4"],
                                   },
                                  ],
                          },
                      ],
                   },
                   ],
              },
            ],
         },
    ],
};*/